### ISSUE TITLE
multi-keyword syntax for flex results in missing semicolon error

### ISSUE THREAD

**Issue by tif-calin** [Anber/wyw-in-js#142]
## Description
When I try to set a rule like `display: flex inline;`, I get an error about a missing semi-colon.
```css
1  |  .Wrapper_w1mbcvav{display:-webkit-boxdisplay:-webkit-flexdisplay:-ms-flexbox inline;display:flex inline;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;background:rgb(var(--power-color-brown));border:2.5mm solid;border-image:url("/assets/brown.webp") 10/0.5;line-height:1;min-height:16mm;}.Wrapper_w1mbcvav>span:first-child{font-weight:500;}
   |                                              ^
```

## Environment
My dependencies:
```json
{
  "dependencies": {
    "@imgly/background-removal": "^1.6.0",
    "@linaria/babel-preset": "^5.0.4",
    "@linaria/core": "^6.3.0",
    "@linaria/react": "^6.3.0",
    "@react-router/node": "^7.4.1",
    "@react-router/serve": "^7.4.1",
    "isbot": "^5",
    "onnxruntime-web": "1.21.0-dev.20250206-d981b153d3",
    "react": "^19.0.0",
    "react-dom": "^19.0.0",
    "react-router": "^7.4.1"
  },
  "devDependencies": {
    "@babel/preset-react": "^7.26.3",
    "@babel/preset-typescript": "^7.27.0",
    "@eslint/js": "^9.21.0",
    "@linaria/vite": "^5.0.4",
    "@react-router/dev": "^7.4.1",
    "@types/node": "^22.14.0",
    "@types/react": "^19.0.10",
    "@types/react-dom": "^19.0.4",
    "@vitejs/plugin-react-swc": "^3.8.0",
    "@wyw-in-js/vite": "^0.6.0",
    "eslint": "^9.21.0",
    "eslint-plugin-react-hooks": "^5.1.0",
    "eslint-plugin-react-refresh": "^0.4.19",
    "globals": "^16.0.0",
    "react-router-devtools": "^1.1.8",
    "typescript": "~5.8.2",
    "typescript-eslint": "^8.24.1",
    "vite": "^6.2.5",
    "vite-tsconfig-paths": "^5.1.4"
  },
  "scripts": { "dev": "vite", "build": "tsc -b && vite build", "lint": "eslint .", "preview": "vite preview" },
  "packageManager": "pnpm@10.7.1+sha512.2d92c86b7928dc8284f53494fb4201f983da65f0fb4f0d40baafa5cf628fa31dae3e5968f12466f17df7e97310e30f343a648baea1b9b350685dafafffdf5808"
```

## Reproducible Demo

If desired, I can push up my repo for reproduction
